const articles = [
"Aquila (constellation)",
"Greek alphabet",
"Sushi",
"Napoleon",
"Solar power",
"Renaissance",
"Sydney Opera House",
"Albert Einstein",
"Tennis",
"Great Barrier Reef",
"Vincent van Gogh",
"Statue of Liberty",
"Artificial intelligence",
"The Beatles",
"Mount Everest",
"Maya civilization",
"Leonardo da Vinci",
"Black hole",
"Marie Curie",
"Taj Mahal",
"Global warming",
"World War II",
"Great Wall of China",
"DNA",
"Queen Elizabeth II",
"Ancient Egypt",
"Pablo Picasso",
"Internet",
"Titanic",
"Buddhism",
"World Cup",
"Albert Einstein",
"Viking Age",
"New York City",
"Ancient Greece",
"Mona Lisa",
"World War I",
"Steve Jobs",
"Michelangelo",
"Space exploration",
"Martin Luther King Jr.",
"Big Bang",
"United Nations",
"Roman Empire",
"Elvis Presley",
"African elephants",
"Charles Darwin",
"Hubble Space Telescope",
"Wolfgang Amadeus Mozart",
"Moon landing",
"Hinduism",
"Internet of things",
"Amsterdam",
"Leonardo DiCaprio",
"Nikola Tesla",
"Machu Picchu",
"Human rights",
"The Simpsons",
"Gravity",
"Walt Disney",
"Climate change",
"Penguins",
"Sigmund Freud",
"Mount Kilimanjaro",
"Ancient Rome",
"Virtual reality",
"Alberto Santos-Dumont",
"Frida Kahlo",
"Apollo 11",
"Barack Obama",
"Mars",
"The Great Gatsby",
"Venice",
"Evolution",
"Marilyn Monroe",
"Abraham Lincoln",
"SpaceX",
"Polar bear",
"Johannes Kepler",
"Paris",
"Steve Jobs",
"Black Mirror",
"Jazz",
"Pompeii",
"Psychology",
"Stephen Hawking",
"Climate change denial",
"Vincent van Gogh's art",
"Neuschwanstein Castle",
"Romeo and Juliet",
"Leonardo da Vinci's inventions",
"Galapagos Islands",
"Google",
"Mount Vesuvius",
"Asgardia"
];  
