// ./scripts/articles.js

function randomArticles(numPossibleArticles) {
    const articles = [
      "Aquila (constellation)",
      "Greek alphabet",
      "Sushi",
      "Napoleon",
      "Solar power",
      "Renaissance",
      "Sydney Opera House",
      "Albert Einstein",
      "Tennis",
      "Great Barrier Reef",
      "Vincent van Gogh",
      "Statue of Liberty",
      "Artificial intelligence",
      "The Beatles",
      "Mount Everest",
      "Maya civilization",
      "Leonardo da Vinci",
      "Black hole",
      "Marie Curie",
      "Taj Mahal",
      "Global warming",
      "World War II",
      "Great Wall of China",
      "DNA",
      "Queen Elizabeth II",
      "Ancient Egypt",
      "Pablo Picasso",
      "Internet",
      "Titanic",
      "Buddhism",
      "World Cup",
      "Albert Einstein",
      "Viking Age",
      "New York City",
      "Ancient Greece",
      "Mona Lisa",
      "World War I",
      "Steve Jobs",
      "Michelangelo",
      "Space exploration",
      "Martin Luther King Jr.",
      "Big Bang",
      "United Nations",
      "Roman Empire",
      "Elvis Presley",
      "African elephants",
      "Charles Darwin",
      "Hubble Space Telescope",
      "Wolfgang Amadeus Mozart",
      "Moon landing",
      "Hinduism",
      "Internet of things",
      "Amsterdam",
      "Leonardo DiCaprio",
      "Nikola Tesla",
      "Machu Picchu",
      "Human rights",
      "The Simpsons",
      "Gravity",
      "Walt Disney",
      "Climate change",
      "Penguins",
      "Sigmund Freud",
      "Mount Kilimanjaro",
      "Ancient Rome",
      "Virtual reality",
      "Alberto Santos-Dumont",
      "Frida Kahlo",
      "Apollo 11",
      "Barack Obama",
      "Mars",
      "The Great Gatsby",
      "Venice",
      "Evolution",
      "Marilyn Monroe",
      "Abraham Lincoln",
      "SpaceX",
      "Polar bear",
      "Johannes Kepler",
      "Paris",
      "Steve Jobs",
      "Black Mirror",
      "Jazz",
      "Pompeii",
      "Psychology",
      "Stephen Hawking",
      "Climate change denial",
      "Vincent van Gogh's art",
      "Neuschwanstein Castle",
      "Romeo and Juliet",
      "Leonardo da Vinci's inventions",
      "Galapagos Islands",
      "Google",
      "Mount Vesuvius",
      "Hawaii",
    "Piano",
    "Julius Caesar",
    "Fossil",
    "Coco Chanel",
    "Gravity Falls",
    "The Matrix",
    "Leonardo da Vinci's The Last Supper",
    "Great Sphinx of Giza",
    "World Health Organization",
    "FIFA World Cup",
    "Vincent van Gogh's Starry Night",
    "Machu Picchu",
    "Quantum mechanics",
    "Winston Churchill",
    "World War I trenches",
    "Nintendo",
    "Mount Rushmore",
    "Surrealism",
    "Pablo Neruda",
    "The Eiffel Tower",
    "Climate change mitigation",
    "Panda",
    "Pablo Picasso's Guernica",
    "Helen Keller",
    "Islam",
    "Berlin Wall",
    "DNA sequencing",
    "René Descartes",
    "Mount Fuji",
    "Ancient China",
    "Industrial Revolution",
    "Oscar Wilde",
    "The Lord of the Rings",
    "Neptune",
    "Dinosaurs",
    "Astronomy",
    "Marie Antoinette",
    "Electricity",
    "Greece",
    "Soccer",
    "Joan of Arc",
    "The Mona Lisa in popular culture",
    "Great Depression",
    "Nelson Mandela",
    "Aristotle",
    "Harry Potter",
    "United States Declaration of Independence",
    "Genetics",
    "Monet",
    "Venus",
    "Sustainable development",
    "Walt Disney World Resort",
    "Claude Monet's Water Lilies",
    "Nikola Tesla",
    "Berlin",
    "The Great Wall of China in popular culture",
    "Leonardo da Vinci's Vitruvian Man",
    "Space Shuttle",
    "Civil rights movement",
    "Frankenstein",
    "The Milky Way",
    "Brazil",
    "Apartheid",
    "The Wizard of Oz",
    "The Hunger Games",
    "Freddie Mercury",
    "Cleopatra",
    "Art Deco",
    "European Union",
    "Frida Kahlo's art",
    "Mount St. Helens",
    "Frank Lloyd Wright",
    "The Simpsons",
    "Christopher Columbus",
    "The Beatles' discography",
    "Soviet Union",
    "Cinematography",
    "Stonehenge",
    "United Kingdom",
    "The Hobbit",
    "Rosa Parks",
    "Mozart's music",
    "Marilyn Monroe",
    "Human evolution",
    "Albert Camus",
    "Pyramids of Giza",
    "Climate change skepticism",
    "Marine biology",
    "European Renaissance",
    "George Orwell",
    "Thomas Edison",
    "Louvre Museum",
    "Antarctica",
    "Geology",
    "Vincent van Gogh's self-portraits",
    "Sustainable energy",
    "Apollo program",
    "Catherine the Great",
    "The Godfather",
    "Genetically modified organisms",
    "Angkor Wat",
    "Leonardo da Vinci's The Birth of Venus",
    "Alaska",
    "Mount Everest",
    "Feminism",
    "Paul Cézanne",
    "Blackbeard",
    "The Great Gatsby",
    "The Louvre",
    "Galileo Galilei",
    "Russian Revolution",
    "Baroque architecture",
    "The Lion King",
    "Quantum physics",
    "Andy Warhol",
    "William Shakespeare's plays",
    "Leonardo da Vinci's Annunciation",
    "Gustav Klimt",
    "Prohibition",
    "Antibiotics",
    "India",
    "Impressionism",
    "The Rolling Stones",
    "Bill Gates",
    "Great Smoky Mountains",
    "Claude Monet's Impression, Sunrise",
    "Atomic bomb",
    "Fibonacci sequence",
    "Edward Snowden",
    "Easter Island",
    "Mount Kilimanjaro",
    "Anne Frank",
    "Leonardo da Vinci's notebooks",
    "Indus Valley Civilization",
    "Marine life",
    "George Washington",
    "Coco Chanel's designs",
    "Ballet",
    "Hernán Cortés",
    "San Francisco",
    "World War II in popular culture",
    "Thomas Jefferson",
    "Charles Dickens",
    "Mayan civilization",
    "The Big Bang Theory",
    "Eiffel Tower",
    "Rome",
    "Walt Disney Animation Studios",
    "Leonardo da Vinci's The Last Judgment",
    "Gandhi",
    "Bauhaus",
    "Antoine de Saint-Exupéry",
    "The Beatles' influence",
    "Machu Picchu in popular culture",
    "Sigmund Freud's theories",
    "Johannes Vermeer",
    "Ancient Greece",
    "Physics",
    "Photography",
    "Einstein's brain",
    "The Little Mermaid",
    "Hawaii in popular culture",
    "The Industrial Revolution in popular culture",
    "Plato",
    "Aviation",
    "Ansel Adams",
    "Hindu mythology",
    "Ireland",
    "Diego Rivera",
    "Leonardo da Vinci's The Creation of Adam",
    "Cleopatra in popular culture",
    "Gravity Falls",
    "Monarch butterfly",
    "Mount Vesuvius",
    "Jane Austen",
    "The Great Gatsby in popular culture",
    "Leonardo da Vinci's science",
    "John F. Kennedy",
    "The Simpsons Movie",
    "British Museum",
    "Abstract art",
    "John Locke",
    "Frank Sinatra",
    "Chemistry",
    "Alhambra",
    "Michelangelo's David",
    "Tolkien",
    "Johannes Kepler's laws of planetary motion",
    "Leonardo da Vinci's Last Supper",
    "The Taj Mahal in popular culture",
    "Charles Darwin's theory of evolution",
    "Photography",
    "Mount Everest in popular culture",
    "The Shawshank Redemption",
    "Cubism",
    "Ancient Egypt in popular culture",
    "Sherlock Holmes",
    "Göbekli Tepe",
    "Sustainable agriculture",
    "Dadaism",
    "Halloween",
    "Jean-Michel Basquiat",
    "Ancient Mesopotamia",
    "The Titanic in popular culture",
    "William Shakespeare",
    "Beethoven",
    "Frida Kahlo's self-portraits",
    "World War I in popular culture",
    "Ancient Greece in popular culture",
    "Georges Méliès"
    
    ];  
    
    var selectedArticles = [];
    var totalElements = articles.length;
  
    while (selectedArticles.length < numPossibleArticles) {
      const randomIndex = Math.floor(Math.random() * totalElements);
      const randomArticle = articles[randomIndex];
      if (!selectedArticles.includes(randomArticle)) {
        selectedArticles.push(randomArticle);
      }
    }
    return selectedArticles;
  }
  